package com.mlnx.shop.entity;

public class TActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.name
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.id
     *
     * @return the value of t_activity.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.id
     *
     * @param id the value for t_activity.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.name
     *
     * @return the value of t_activity.name
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.name
     *
     * @param name the value for t_activity.name
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }
}