package com.mlnx.shop.entity;

public class TClassify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classify.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classify.name
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private String name;
    
    private Integer parent_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classify.id
     *
     * @return the value of t_classify.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classify.id
     *
     * @param id the value for t_classify.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classify.name
     *
     * @return the value of t_classify.name
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classify.name
     *
     * @param name the value for t_classify.name
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

	public Integer getParent_id() {
		return parent_id;
	}

	public void setParent_id(Integer parent_id) {
		this.parent_id = parent_id;
	}
    
    
}