package com.mlnx.shop.entity;

import java.util.Date;

public class TGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.date
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.price
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.name
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.pic
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.type
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.score
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer store;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.classify_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer classifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.populartiy
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer populartiy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.sales
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer sales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.activitiy_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer activitiyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.description
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private String description;
    
    private Integer valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.id
     *
     * @return the value of t_goods.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.id
     *
     * @param id the value for t_goods.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.date
     *
     * @return the value of t_goods.date
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.date
     *
     * @param date the value for t_goods.date
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.price
     *
     * @return the value of t_goods.price
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.price
     *
     * @param price the value for t_goods.price
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.name
     *
     * @return the value of t_goods.name
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.name
     *
     * @param name the value for t_goods.name
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.pic
     *
     * @return the value of t_goods.pic
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.pic
     *
     * @param pic the value for t_goods.pic
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.type
     *
     * @return the value of t_goods.type
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.type
     *
     * @param type the value for t_goods.type
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.score
     *
     * @return the value of t_goods.score
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getStore() {
        return store;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.store
     *
     * @param store the value for t_goods.store
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setStore(Integer store) {
        this.store = store;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.classify_id
     *
     * @return the value of t_goods.classify_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getClassifyId() {
        return classifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.classify_id
     *
     * @param classifyId the value for t_goods.classify_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setClassifyId(Integer classifyId) {
        this.classifyId = classifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.populartiy
     *
     * @return the value of t_goods.populartiy
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getPopulartiy() {
        return populartiy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.populartiy
     *
     * @param populartiy the value for t_goods.populartiy
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setPopulartiy(Integer populartiy) {
        this.populartiy = populartiy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.sales
     *
     * @return the value of t_goods.sales
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.sales
     *
     * @param sales the value for t_goods.sales
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.activitiy_id
     *
     * @return the value of t_goods.activitiy_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getActivitiyId() {
        return activitiyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.activitiy_id
     *
     * @param activitiyId the value for t_goods.activitiy_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setActivitiyId(Integer activitiyId) {
        this.activitiyId = activitiyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.description
     *
     * @return the value of t_goods.description
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.description
     *
     * @param description the value for t_goods.description
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

	public Integer getValid() {
		return valid;
	}

	public void setValid(Integer valid) {
		this.valid = valid;
	}

	@Override
	public String toString() {
		return "TGoods [id=" + id + ", date=" + date + ", price=" + price
				+ ", name=" + name + ", pic=" + pic + ", type=" + type
				+ ", store=" + store + ", classifyId=" + classifyId
				+ ", populartiy=" + populartiy + ", sales=" + sales
				+ ", activitiyId=" + activitiyId + ", description="
				+ description + ", valid=" + valid + "]";
	}
}