package com.mlnx.shop.entity;

import java.util.Date;

public class TOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.name
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.date
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.state
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.goods_ids
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private String goodsIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.name
     *
     * @return the value of t_order.name
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.name
     *
     * @param name the value for t_order.name
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.date
     *
     * @return the value of t_order.date
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.date
     *
     * @param date the value for t_order.date
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.state
     *
     * @return the value of t_order.state
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.state
     *
     * @param state the value for t_order.state
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.goods_ids
     *
     * @return the value of t_order.goods_ids
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public String getGoodsIds() {
        return goodsIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.goods_ids
     *
     * @param goodsIds2 the value for t_order.goods_ids
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setGoodsIds(String goodsIds) {
        this.goodsIds = goodsIds;
    }
}