package com.mlnx.shop.entity;

public class TUserAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_address.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_address.user_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_address.address
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_address.id
     *
     * @return the value of t_user_address.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_address.id
     *
     * @param id the value for t_user_address.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_address.user_id
     *
     * @return the value of t_user_address.user_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_address.user_id
     *
     * @param userId the value for t_user_address.user_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_address.address
     *
     * @return the value of t_user_address.address
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_address.address
     *
     * @param address the value for t_user_address.address
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }
}