package com.mlnx.shop.entity;

public class TUserExt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ext.user_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ext.pic
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ext.nickname
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ext.integral
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer integral;
    
    private Double money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ext.user_id
     *
     * @return the value of t_user_ext.user_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ext.user_id
     *
     * @param userId the value for t_user_ext.user_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ext.pic
     *
     * @return the value of t_user_ext.pic
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ext.pic
     *
     * @param pic the value for t_user_ext.pic
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ext.nickname
     *
     * @return the value of t_user_ext.nickname
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ext.nickname
     *
     * @param nickname the value for t_user_ext.nickname
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ext.integral
     *
     * @return the value of t_user_ext.integral
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ext.integral
     *
     * @param integral the value for t_user_ext.integral
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

	public Double getMoney() {
		return money;
	}

	public void setMoney(Double money) {
		this.money = money;
	}

	@Override
	public String toString() {
		return "TUserExt [userId=" + userId + ", pic=" + pic + ", nickname="
				+ nickname + ", integral=" + integral + ", money=" + money
				+ "]";
	}
}