package com.mlnx.shop.entity;

public class TUserCoupon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_coupon.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_coupon.user_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_coupon.coupon_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer couponId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_coupon.id
     *
     * @return the value of t_user_coupon.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_coupon.id
     *
     * @param id the value for t_user_coupon.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_coupon.user_id
     *
     * @return the value of t_user_coupon.user_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_coupon.user_id
     *
     * @param userId the value for t_user_coupon.user_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_coupon.coupon_id
     *
     * @return the value of t_user_coupon.coupon_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_coupon.coupon_id
     *
     * @param couponId the value for t_user_coupon.coupon_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }
}