package com.mlnx.shop.entity;

public class TUserCollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_collection.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_collection.user_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_collection.collection_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    private Integer collectionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_collection.id
     *
     * @return the value of t_user_collection.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_collection.id
     *
     * @param id the value for t_user_collection.id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_collection.user_id
     *
     * @return the value of t_user_collection.user_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_collection.user_id
     *
     * @param userId the value for t_user_collection.user_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_collection.collection_id
     *
     * @return the value of t_user_collection.collection_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public Integer getCollectionId() {
        return collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_collection.collection_id
     *
     * @param collectionId the value for t_user_collection.collection_id
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    public void setCollectionId(Integer collectionId) {
        this.collectionId = collectionId;
    }
}