package com.mlnx.shop.mapper;

import java.util.List;

import com.mlnx.shop.entity.TActivity;

public interface TActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    int insert(TActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    TActivity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    List<TActivity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    int updateByPrimaryKey(TActivity record);
}