package com.mlnx.shop.mapper;

import java.util.List;

import com.mlnx.shop.entity.TClassify;

public interface TClassifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classify
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classify
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    int insert(TClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classify
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    TClassify selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classify
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    List<TClassify> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classify
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    int updateByPrimaryKey(TClassify record);
}