package com.mlnx.shop.mapper;

import java.util.List;
import java.util.Map;

import com.mlnx.shop.entity.TGoods;

public interface TGoodsMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_goods
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_goods
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	int insert(TGoods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_goods
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	TGoods selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_goods
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	List<TGoods> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_goods
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	int updateByPrimaryKey(TGoods record);

	/**
	 * 根据条件查找商品
	 * 
	 * @param map
	 * @return
	 */
	List<TGoods> selectByMap(Map<String, Object> map);
}