package com.mlnx.shop.mapper;

import java.util.List;

import com.mlnx.shop.entity.TUserExt;

public interface TUserExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ext
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ext
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    int insert(TUserExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ext
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    TUserExt selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ext
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    List<TUserExt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ext
     *
     * @mbggenerated Thu Dec 24 14:12:26 CST 2015
     */
    int updateByPrimaryKey(TUserExt record);
}