package com.mlnx.shop.mapper;

import java.util.List;

import com.mlnx.shop.entity.TUserAddress;

public interface TUserAddressMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user_address
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user_address
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	int insert(TUserAddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user_address
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	TUserAddress selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user_address
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	List<TUserAddress> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user_address
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	int updateByPrimaryKey(TUserAddress record);

	/**
	 * 获取用户地址
	 * 
	 * @param user_id
	 * @return
	 */
	List<String> findAddressById(int user_id);
}