package com.mlnx.shop.mapper;

import java.util.List;

import com.mlnx.shop.entity.TUser;

public interface TUserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * to the database table t_user
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	int insert(TUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	TUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	List<TUser> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	int updateByPrimaryKey(TUser record);

	/**
	 * 根据手机号获取用户
	 * 
	 * @param phone
	 * @return
	 */
	TUser selectByPhone(String phone);

}