package com.mlnx.shop.mapper;

import java.util.List;

import com.mlnx.shop.entity.TCoupon;
import com.mlnx.shop.entity.TUserCoupon;

public interface TUserCouponMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user_coupon
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user_coupon
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	int insert(TUserCoupon record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user_coupon
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	TUserCoupon selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user_coupon
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	List<TUserCoupon> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user_coupon
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	int updateByPrimaryKey(TUserCoupon record);

	/**
	 * 获取优惠券列表
	 * 
	 * @param user_id
	 * @return
	 */
	List<Integer> findCouponById(int user_id);

	/**
	 * 查看个人优惠券
	 * 
	 * @param id
	 * @return
	 */
	List<TCoupon> findCouponsById(Integer id);
}