package com.mlnx.shop.mapper;

import java.util.List;

import com.mlnx.shop.entity.TUserCollection;

public interface TUserCollectionMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user_collection
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user_collection
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	int insert(TUserCollection record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user_collection
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	TUserCollection selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user_collection
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	List<TUserCollection> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user_collection
	 * 
	 * @mbggenerated Thu Dec 24 14:12:26 CST 2015
	 */
	int updateByPrimaryKey(TUserCollection record);

	/**
	 * 根据用户id查找收藏id列表
	 * 
	 * @param user_id
	 * @return
	 */
	List<Integer> findCollectionById(int user_id);
}